### ISSUE TITLE
aws credentials not found

### ISSUE THREAD

**Issue by rickyroma0** [logandk/serverless-wsgi#104]
I've deployed a simple flask app to aws with serverless (at this point it really just inserts/reads some values to/from a dynamodb table) and it's working as it's supposed to. 
I set up several aws credentials profiles and when I deploy to aws I use '--aws-profile <profile>' option. 

What I'm trying to do now is to run this locally to avoid the lengthy edit/deploy/test cycle with aws. However when I try to run it with 'sls wsgi serve' and then try to execute the functions, I get an error 'botocore.exceptions.NoCredentialsError: Unable to locate credentials'. I've tried adding '--aws-profile <profile>' option to 'sls wsgi serve' command, but that didn't make any difference. 

Is there a way to pass aws credentials profile to wsgi while running the app locally?

**Comment by logandk** [comment]
I'd suggest you try setting the `AWS_PROFILE` environment variable to the name of your profile. See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by logandk** [comment]
I.e. `$ AWS_PROFILE=yourprofile sls wsgi serve`
