### ISSUE TITLE
Throwing exception instead of outputing the error

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [logandk/serverless-wsgi#107]
Hi,
Thanks for this awesome plugin :D

I would like to run nosetests with env vars from serverless.yml, and I found that I could run it with this plugin like this `sls wsgi command local -c "nosetests"` and it worked fine if all the tests run without error.
but if my code throws any error e.g. exception, instead of outputing that error, it prints this message:

```
Traceback (most recent call last):\n  File \"./wsgi_handler.py\", line 82, in handler\n

meta.get(\"data\", \"\"), shell=True, stderr=subprocess.STDOUT\n  File \"/usr/lib64/python3.7/subprocess.py\", line 395, in check_output\n

**kwargs).stdout\n  File \"/usr/lib64/python3.7/subprocess.py\", line 487, in run\n

output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command 'nosetests --cover-package src' returned non-zero exit status 1.
```

Also the formatting is incorrect  (printing a string instead of parsing the newlines and any other escaped char)

Thanks in advance

**Comment by logandk** [comment]
Yes, appears that we'll need to improve the output when the command being called fails. For now, as an alternative, consider incorporating the https://github.com/arabold/serverless-export-env plugin in your workflow.

**Comment by AhmedNourJamalElDin** [comment]
Hi @logandk 

Why do not we reject the promise here instead of swallow the exception?

https://github.com/logandk/serverless-wsgi/blob/e596820dee9b1c3cbff9a2981c2630da145d1d73/index.js#L488

**Comment by logandk** [comment]
@AhmedNourJamalElDin I think this was done in order to mimic how the `invoke` command handled and displayed error messages at the time. It might work differently in serverless now, so that rejecting the promise yields a useful error message. If you try it out and find that it works better, I'm open to accepting that change.
