### ISSUE TITLE
Error while migrate command from Serverless

### ISSUE THREAD

**Issue by pankajpant22** [logandk/serverless-wsgi#108]
Hi,
Thanks for this awesome plugin :D

I would like to run flask migrate db commands and I found that I could run it with this plugin like this sls wsgi flask -c "db" and it worked fine. I get options as 

`Usage: bootstrap db [OPTIONS] COMMAND [ARGS]...
  Perform database migrations.
Options:
  --help  Show this message and exit.
Commands:
  branches   Show current branch points
  current    Display the current revision for each database.
  downgrade  Revert to a previous version
  edit       Edit a revision file
  heads      Show current available heads in the script directory
  history    List changeset scripts in chronological order.
  init       Creates a new migration repository.
  merge      Merge two revisions together, creating a new revision file
  migrate    Autogenerate a new revision file (Alias for 'revision...
  revision   Create a new revision file.
  show       Show the revision denoted by the given symbol.
  stamp      'stamp' the revision table with the given revision; don't run...
  upgrade    Upgrade to a later version`

But when I run sls wsgi flask -c "db init",  I get an error :

`  File "/var/task/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/task/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/var/task/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/var/task/flask_migrate/cli.py", line 31, in init
    _init(directory, multidb)
  File "/var/task/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/var/task/flask_migrate/__init__.py", line 125, in init
    directory = current_app.extensions['migrate'].directory
KeyError: 'migrate'`

When I run the same command from command line as 

> python manage.py db init :  It Works

Please Help Me,

Thanks,

**Comment by logandk** [comment]
@pankajpant22 Could you provide a minimal reproduction setup?

**Comment by pankajpant22** [comment]
Thanks a lot 👍 I have a Flask application with Flask-Migrate and Flask-Script setup. Everything works fine when using flask commands from command prompt. The problem comes when I run command from sls wsgi ( sls wsgi flask -c "db init") it gives KeyError.

If you want i can give you the Github Link for the project.

**Comment by logandk** [comment]
Sorry, I didn't have time to work on this for a while. I'll close the issue for now - if you still have a reproduction setup, please post the link and reopen the issue.
