### ISSUE TITLE
Properly handle multiple set cookies in output

### ISSUE THREAD

**Issue by bbangert** [logandk/serverless-wsgi#11]
Due to a quirk in API Gateway, multiple set-cookie's will be dropped to a single one. Mangling the case of the set-cookie header is sufficient to pass them through though.

This pluging should do the case mangling on the way out, perhaps via middleware as Zappa does, to remedy this. Here's what my PR to Zappa to do this looked like:
https://github.com/Miserlou/Zappa/pull/636

The final code is fairly simple, perhaps it can be more directly incorporated into the WSGI handler:
https://github.com/Miserlou/Zappa/blob/master/zappa/middleware.py

**Comment by logandk** [comment]
Indeed, it looks like that hack is the only way to have multiple cookies at this point (except for cases where it's viable to put multiple cookies into a single `Set-Cookie` header).

Thanks for linking your original PR, I'll grab the code and get it into `serverless-wsgi` as well.

**Comment by logandk** [comment]
Will be included in next release (1.1.0)
