### ISSUE TITLE
Force restart wsgi.

### ISSUE THREAD

**Issue by sakoht** [logandk/serverless-wsgi#111]
I have a flask app that does some caching.  I'd like to be able to restart it without redeploying the app.

So far the only way I've found to do this is run "ps ax" to find the `/var/lang/bin/python3.7 /var/runtime/bootstrap` process and kill it.

Is there a more elegant way?

**Comment by logandk** [comment]
I would suggest implementing the cache invalidation in a way that doesn't require the app to be restarted. Killing the process will only restart the application on a single container, but it might be running on concurrent containers as well.
