### ISSUE TITLE
Redirecting to HTTP

### ISSUE THREAD

**Issue by cbare** [logandk/serverless-wsgi#113]
Let's say I define a route with a trailing slash `@app.route("/hello/", methods=('GET',))` but I make a request that omits the trailing slash. Flask's ordinary behavior is to help the caller out by redirecting to the URL with the trailing slash.

Somewhere in the chain API-Gateway - Lambda - serverless-wsgi - Flask this behavior breaks by redirecting to an http url rather than https. For example, in my 'dev' stage, requesting:

> curl -v https://vxxxxxxxk.execute-api.us-west-2.amazonaws.com/dev/hello

...returns a 308 with the following header (notice the 'http'):

Location: **http**://vxxxxxxxk.execute-api.us-west-2.amazonaws.com/dev/hello/

Not sure if this is a bug, or whose bug it is...

**Comment by logandk** [comment]
I've tried reproducing this using a simple Flask app with a route that includes a trailing slash, as you've described. When I make a request to the URL without the trailing slash, I'm correctly redirected to the URL with the trailing slash and the same protocol (https). So I'm not able to replicate your issue at this point.

I'll close the issue for now. If you have a simple replication setup, please reopen and provide the code that demonstrates the issue.

**Comment by cbare** [comment]
Hi Logan, thanks for having a look - much appreciated. If you're not able to repro, that makes me suspect something in my AWS configuration may be at fault. Will report back if I get any better insight. Thanks!
