### ISSUE TITLE
Support lambda layers

### ISSUE THREAD

**Issue by joecarp** [logandk/serverless-wsgi#117]
I'm using serverless-python-requirements to deploy a lot of my various lambda dependencies as layers. I can't use layers with the ones that use serverless-wsgi, as it only supports the zip dependency method. 

Any current plans for adding layer support? I have a partial implementation right now, but I don't want to step on any toes if others are looking at this already.

**Comment by logandk** [comment]
@joecarp I am not working on adding layer support, so if you have an implementation already, I'd appreciate if you'd share it - thanks.

**Comment by logandk** [comment]
I'm assuming that you're able to use serverless-python-requirements to handle packaging and utilize layers, in which case the packaging feature of serverless-wsgi will be disabled anyway. Closing this issue, but let me know if you're willing to share your implementation.
