### ISSUE TITLE
Bad error message on failed requirements.txt installation

### ISSUE THREAD

**Issue by christopher-dG** [logandk/serverless-wsgi#122]
I had a bad version that did not actually exist in my `requirements.txt`, and `sls deploy` output this:

```
Serverless: Using Python specified in "runtime": python3.8
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...
 
 Exception -----------------------------------------------
 
  <Buffer 45 52 52 4f 52 3a 20 43 6f 75 6c 64 20 6e 6f 74 20 66 69 6e 64 20 61 20 76 65 72 73 69 6f 6e 20 74 68 61 74 20 73 61 74 69 73 66 69 65 73 20 74 68 65 ... 2105 more bytes>
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.5.0
     Framework Version:         1.59.3
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
Seems like the error throwing code has a bug.

**Comment by mfsjr** [comment]
Same problem here, reported to Serverless here: https://github.com/serverless/serverless/issues/7084.

There advice was to remove plugins to determine which plugin is causing the problem, I did, and it is this one.

**Comment by logandk** [comment]
Thanks for reporting, I'll try reproducing this

**Comment by babyhuey** [comment]
I've been getting the same issue a lot lately. Once I was able to deactivate the virtual environment and it worked. 

If there was some way to fully print the Buffer, I think that would be a good help to figure out the whole issue

**Comment by harshthakur9030** [comment]
I'm facing similar issue. Is there a temporary solution?

**Comment by babyhuey** [comment]
> 
> 
> I'm facing similar issue. Is there a temporary solution?

When I remove `packRequirements: true` from my serverless.yml, that seems to fix it. Just make sure you have `werkzeug` in your requirements

**Comment by harshthakur9030** [comment]
Got it. The problem is with packRequirements: true . I had to explicitly set it to false to make it work as the default seems to be true.

**Comment by mfsjr** [comment]
Changing packRequirements to false allowed my serverless deployment to go through as well.
