### ISSUE TITLE
integration with SNS

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [logandk/serverless-wsgi#123]
Is there any reasonable way of integrating this with AWS SNS?

When I naively subscribe my deployed lambda to an SNS topic I get:
```
[ERROR] KeyError: 'headers'
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 109, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 96, in handle_request
    headers = Headers(event[u"headers"])
```

Obviously the request headers are missing; I'm wondering if there's a workaround or if this use case is just silly?

**Comment by adriantomas** [comment]
Hi @ConstantinoSchillebeeckxSimpleRose I'm experiencing the same issue with a DynamoDB Stream.
```
functions:
  dynamodbStream:
    handler: wsgi_handler.handler
    role: ESIAMRole
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn: !ImportValue ${self:custom.stage}-TableStreamArn
```

Maybe it's a problem related to both situations

**Comment by logandk** [comment]
Yes, this isn't really a use case for serverless-wsgi. It's meant for HTTP requests coming through API Gateway or ALB.

I would advise you to have a separate non-WSGI handler in your application to accept these events.

For DynamoDB, @adriantomas, see https://github.com/logandk/instawat
