### ISSUE TITLE
Move auto-generated, transient files to .serverless folder

### ISSUE THREAD

**Issue by mungojam** [logandk/serverless-wsgi#126]
If I have understood correctly, there are 3 files that are auto-generated by the plugin and at present they all end up being written to the current directory:

- .serverless-wsgi
- serverless_wsgi.py
- wsgi_handler.py

I've added these manually to my `.gitignore` as presumably they might get updated in later versions of the tool, but it would be cleaner for us if they went into a sub-folder of the `.serverless` folder which is generally in `.gitignore` already and is presumably meant for transient files.

It could be that I'm missing something about how it all works though

**Comment by logandk** [comment]
This is correct. The `cwd` is what gets packaged and ends up in the zip file that gets deployed. The `.serverless` directory is not going to be deployed and it would be useless in this context to write files there. After deployment, the files are supposed to be removed automatically by the plugin. I.e. they only exist in `cwd` for the duration of the `sls deploy` command.

If they're still lingering in your `cwd` after deployment is complete, then something's wrong. Additionally, you may call `sls wsgi clean` to perform the clean up step manually.

I'm closing this issue, feel free to reopen if you believe something's wrong - e.g. if the files are not removed when deployment has completed.
