### ISSUE TITLE
Not getting data for request.values in Flask restfull app

### ISSUE THREAD

**Issue by jadhavmanoj** [logandk/serverless-wsgi#129]
Hi, 

I am building a Lambda service using flask restful. I want to use Request parser (reqparse.RequestParser()) to parse arguments. It takes a  data from `request.values` internally.

But I can see, In serverless, we are adding event and context in environ variable.

is there any workaround for this?

Though I can access by using request

from flask import request
`request.environ`  I can see all data.

Thanks in advance.

**Comment by logandk** [comment]
Hi,
The `request.args`, `request.form` and `request.values` methods should operate as normally. It's true that `event` and `context` are also added to the request `environ`, in case you need to dig into the raw event. But it sounds like this isn't necessary in your case.

If you have a specific issue with accessing `request.values`, please set up a repo that will show how to reproduce the issue. I'm closing this issue for now.
