### ISSUE TITLE
Poetry and "Unable to import werkzeug (run: pip install werkzeug)"

### ISSUE THREAD

**Issue by maxcountryman** [logandk/serverless-wsgi#131]
I keep running into this error when trying to run `$ sls wsgi serve` when using Poetry for dependency management:

`Unable to import werkzeug (run: pip install werkzeug)`

`werkzeug` is included in my `pyproject.toml` so my best guess is `sls wsgi` is not using the correct Python version or perhaps Poetry-managed virtualenv.

Any guidance on how to make this plugin play nicely with Poetry would be appreciated. Also note I'm having to use `pyenv` so that Poetry has access to Python 3.

**Comment by bruceadams** [comment]
For me, the problem is hinted at in the messages:

```bash
$ sls wsgi serve
Serverless: Using Python specified in "runtime": python3.7
Unable to import werkzeug (run: pip install werkzeug)
```

The problem is that `python3.7` is not within the [Poetry](https://python-poetry.org/) virtualenv. `python` and `python3` are managed by [Poetry](https://python-poetry.org/).

```bash
$ type -f python3.7
python3.7 is hashed (/usr/local/bin/python3.7)
$ type -f python
python is hashed (/Users/bruce/Library/Caches/pypoetry/virtualenvs/my-api-AO4b-1bH-py3.7/bin/python)
$ type -f python3
python3 is /Users/bruce/Library/Caches/pypoetry/virtualenvs/my-api-AO4b-1bH-py3.7/bin/python3
```

Adding a custom `pythonBin` in my `serverless.yml` gets me running! 🎉 The last line here:

```yaml
service: example

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: my.app
    pythonBin: python
```

**Comment by logandk** [comment]
@bruceadams Thanks for helping out here - and this is indeed the type of scenario that `pythonBin` is intended for. By now there are many different constellations of python dependency management solutions out there and I don't intend this plugin to cover anything except a pretty standard configuration out of the box.

The main purpose is wrapping the WSGI application and using generic options like `pythonBin` should be enough to cover most use cases. I.e. there won't be any specific support added for Poetry or the likes of it. I'm happy to accept PRs with improvements for the `README` with specific notes for other Poetry users.
