### ISSUE TITLE
Adding Serverless Dashboard's required app: in serverless.yaml breaks functionality 

### ISSUE THREAD

**Issue by promediacorp** [logandk/serverless-wsgi#138]
Serverless Dashboard adds` app: app-name` in the serverless.yaml

when this is added, the application will not work and return 

`Exception: Unable to import application.application` when running in lambda.

The presense of two instances of app: might be causeing the issues

Removing the line and redeploying resolves the problem

**Comment by logandk** [comment]
I haven't used Serverless Dashboard. Could you elaborate?

Does this only happen once? (i.e. upon initial configuration of the Dashboard)
Where in `serverless.yaml` exactly does the line get added? Can you include a more complete example?
You can remove the line and redeploy, but will Serverless Dashboard then stop working?

**Comment by promediacorp** [comment]
i had a chat with a serverless engineer and it turns out that if the function name is named 'app' it breaks because of a regex bug on their end which they have a ticket to fix. the temporary solution was to just renamed the function to something else.
