### ISSUE TITLE
Please release a new npm package. I get an error using the latest npm release while github master works fine

### ISSUE THREAD

**Issue by casertap** [logandk/serverless-wsgi#140]
Hi, the latest npm package is 6 months old and does not work for my deployment.
I would like to tell you more about it but this is my error message
```
54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 68 6f 6d 65 2f 74
```
translate to 
```
Traceback (most recent call last):
  File "/home/t
```
I used `    "serverless-wsgi": "git+https://github.com/logandk/serverless-wsgi.git"` on my package.json and my deploy worked fine.

I am wondering why you wouldn't want to release a new version of the package on npm?
Thanks

**Comment by logandk** [comment]
I was hoping to get a few more issues closed before making the release, but didn't find the time to do so. Making a release with what's in `master` at this stage.
