### ISSUE TITLE
Packaging error with v1.7.5 (it works in 1.7.4)

### ISSUE THREAD

**Issue by ramgrandhi** [logandk/serverless-wsgi#142]
Hello -
Thanks for the new release. 

But, I see that my existing sls configuration is not deploying successfully with v1.7.5, so, I pinned down to v1.7.4 and it goes smooth. 

**My environment:**
````
117   Your Environment Information ---------------------------
118      OS:                     linux
119      Node Version:           8.17.0
120      Serverless Version:     1.45.0
````

**sls deploy with serverless-wsgi@1.7.5** ❌

````
Serverless: Installing plugin "serverless-wsgi@latest" (this might take a few seconds...)
104 Serverless: Successfully installed "serverless-wsgi@latest"
107  
108   Serverless Error ---------------------------------------
109  
110   Serverless plugin "serverless-wsgi" initialization errored: Unexpected token {
111  
````

**sls deploy with serverless-wsgi@1.7.4** ✅
````
103 Serverless: Installing plugin "serverless-wsgi@1.7.4" (this might take a few seconds...)
104 Serverless: Successfully installed "serverless-wsgi@1.7.4"
107 Serverless: Using Python specified in "runtime": python3.7
108 Serverless: Packaging Python WSGI handler...
....
....
112 Serverless: Running ...
113 Serverless: Packaging service...
114 Serverless: Excluding development dependencies...
115 Serverless: Injecting required Python packages to package...
````

Appreciate your effort.

Cheers!

**Comment by logandk** [comment]
There's only a single change in the plugin itself between these versions: https://github.com/logandk/serverless-wsgi/compare/1.7.4...master#diff-168726dbe96b3ce427e7fedce31bb0bc

Several dependencies were upgraded as well, which may be causing this. You're running Node 8, which is EOL, so I'd sugges you update to a supported Node version and see if the issue persists. Please reopen if that does not help.
