### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by bjorntheart** [logandk/serverless-wsgi#15]
Hi.

I see the following error in my Lambda function Cloudwatch Logs when using this serverless plugin.

```
START RequestId: f5509b02-3c75-11e7-8d94-d97b07264760 Version: $LATEST
Syntax error in module 'wsgi': Missing parentheses in call to 'print' (wsgi.py, line 118)

END RequestId: f5509b02-3c75-11e7-8d94-d97b07264760
```

It seems that the print statement without parenthesis is not compatible with Python 3.6.

Any chance you'll be porting the plugin to a 3.6 compatible version soon?

**Comment by logandk** [comment]
I would like for the plugin to support 3.6 now that AWS Lambda has added support, planning this for the next version

**Comment by logandk** [comment]
Tests are now passing on Python 3

**Comment by bjorntheart** [comment]
@logandk Wow! That was quick. Great work
