### ISSUE TITLE
Debugging using vscode

### ISSUE THREAD

**Issue by pharindoko** [logandk/serverless-wsgi#159]
Hi,

@logandk thanks for that great plugin. 

I have not been able to debug the code.
Does anyone know how to debug using sls wsgi and vscode ?

br

Florian

**Comment by logandk** [comment]
Hi Florian, no clue about that, sorry - I only use vim. Looks like no one else came up with a good answer, so I'll close this for now.

**Comment by pharindoko** [comment]
We used debugpy then ...
