### ISSUE TITLE
Amazon Linux Causes .requirments Folder To Be Empty

### ISSUE THREAD

**Issue by zaforic** [logandk/serverless-wsgi#16]
Everything is working on CentOS 7.x. If I run the exact same sample code on an Amazon Linux instance the .requirements folder is missing from the zip file. I ran the `python requirements.py requirements.txt .requirements` command and it just creates and empty .requirements folder.

One thing that had to be done was to run `yum remove python27-virtualenv`. This fixed issues with the serverless framework. I believe the issue is related to some pip package issue. I have listed the pre-installed pip packeages on the system below.

aws-cfn-bootstrap (1.4)
awscli (1.11.83)
Babel (0.9.4)
backports.ssl-match-hostname (3.4.0.2)
boto (2.42.0)
botocore (1.5.46)
chardet (2.0.1)
cloud-init (0.7.6)
colorama (0.2.5)
configobj (4.7.2)
docutils (0.11)
ecdsa (0.11)
futures (3.0.3)
gyp (0.1)
iniparse (0.3.1)
jmespath (0.9.2)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
lockfile (0.8)
paramiko (1.15.1)
PIL (1.1.6)
pip (9.0.1)
ply (3.4)
pyasn1 (0.1.7)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pystache (0.5.3)
python-daemon (1.5.2)
python-dateutil (2.1)
pyxattr (0.5.0)
PyYAML (3.10)
requests (1.2.3)
rsa (3.4.1)
setuptools (12.2)
simplejson (3.6.5)
six (1.8.0)
urlgrabber (3.10)
urllib3 (1.8.2)
virtualenv (15.1.0)
yum-metadata-parser (1.1.4)

**Comment by logandk** [comment]
Thanks for the additional info, I'll try debugging it on Amazon Linux

**Comment by logandk** [comment]
There's a new release out, which will hopefully fix this issue. Otherwise, please reopen.
