### ISSUE TITLE
Support for ASGI (starlette, FastAPI)

### ISSUE THREAD

**Issue by dazza-codes** [logandk/serverless-wsgi#162]
Is there any chance this project can also support ASGI frameworks?  The listed forks of this project are not easy to review to see if any work has been done to try to support ASGI.  Some google results for serverless-asgi point to Mangum.

- https://forum.serverless.com/t/does-anyone-know-of-a-python-asgi-plugin/8794
- https://github.com/jordaneremieff/mangum

**Comment by logandk** [comment]
I think mangum is the way to go for ASGI. A mangum plugin for serverless would probably be useful, but I consider it outside the scope of this project.
