### ISSUE TITLE
Feature request for serve command

### ISSUE THREAD

**Issue by njaysoftware** [logandk/serverless-wsgi#166]
Hi All,

It would be nice if the `serve --ssl` command had an option for passing custom cert files to the `werkzeug.run_simple()`. It looks like now when the `--ssl` flag is used that this value will always be 'ad-hoc' which means werkzeug generates its own self-assigned certs on the fly.

The reason why it would be nice to pass custom cert files is that I have been having issues with browsers trusting the werkzeug self-generated cert files.

If you guys think this might be a useful feature, then I am willing to try and make the code changes for it.

**Comment by logandk** [comment]
Sounds like a useful feature, happy to accept a PR
