### ISSUE TITLE
Django Rest Framework static assets return 404

### ISSUE THREAD

**Issue by bjorntheart** [logandk/serverless-wsgi#17]
I am using the serverless-wsgi with a Django Rest Framework project. 

Using the browsable API functionality of DRF, when I run the local server using ```sls wsgi serve -p 8000```, I get loads of 404 errors for the rest framework's static files. When I run the local server using ```./manage.py runserver```, I get no 404 errors. 

EDIT: Not a big deal, since I am not going to use the browsable api functionality in production anyways, but it's great for testing locally

See the contrasting screenshots below

<img width="1176" alt="screen shot 2017-05-31 at 14 28 22" src="https://cloud.githubusercontent.com/assets/53244/26632273/bc9eed1e-460f-11e7-85d3-73eb701d0a68.png">

<img width="428" alt="screen shot 2017-05-31 at 14 28 09" src="https://cloud.githubusercontent.com/assets/53244/26632123/b97e96e4-460e-11e7-9c9a-9653c65a01ec.png">

**Comment by logandk** [comment]
Static files are not served through WSGI by Django (https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/#serving-files)

During development, something like https://github.com/kennethreitz/dj-static may be of use. In a production setup, I would advise against serving static assets through Lambda regardless, it would be cheaper and perform better to put them directly on S3 or a CDN.

**Comment by bjorntheart** [comment]
Logan, I totally agree that the assets should be served from S3 or a CDN. Thanks for the useful links.
