### ISSUE TITLE
Function "undefined" doesn't exist in this Service

### ISSUE THREAD

**Issue by lephuongbg** [logandk/serverless-wsgi#170]
With latest serverless version (2.32.1), running `sls wsgi flask --command "task migrate up"` results in following error:

```
Serverless Error ----------------------------------------
 
  Function "undefined" doesn't exist in this Service
```

I'll hope it will be fixed soon. We currently need to pin serverless version to avoid this issue.

**Comment by DataHighlands** [comment]
I had the same issue, it worked after I downgrade serverless package to version (2.31.0) using below command:

npm install serverless@2.31.0 -g

**Comment by logandk** [comment]
I believe it's related to #156.

**Comment by carlosfunk** [comment]
I've tried downgrading and still get this error running `sls wsgi manage --command`

```
Serverless: Running "serverless" installed locally (in service node_modules)
 
 Serverless Error ----------------------------------------
 
  Function "undefined" doesn't exist in this Service
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         2.31.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

**Comment by lephuongbg** [comment]
@logandk Why is this issue closed when it has not yet been resolved? The issue that you linked has also already been closed.

**Comment by logandk** [comment]
Closed in favor of #156. @mmoallemi99 is preparing a PR

**Comment by george-silva** [comment]
@logandk any workarounds? I'd be happy to help with a fix.

**Comment by george-silva** [comment]
I have been debugging the code and I was able to execute a workaround here with:

`sls invoke -f myfn --stage=production --data '{"_serverless-wsgi":{"command":"manage","data":"check"}}'`

This will execute the `python manage.py check` remotely.
