### ISSUE TITLE
AWS API Gateway Stage Variables Access

### ISSUE THREAD

**Issue by sinner** [logandk/serverless-wsgi#175]
Taking into account we don't have direct access to the API Gateway Stage Variables because our controllers/handlers don't have access to the event parameter, then I was wondering if there is a way to have access to those stage variables or to the event object of the normal lambda functions in python.

**Comment by logandk** [comment]
@sinner You can actually access the event parameter, as described here: https://github.com/logandk/serverless-wsgi#raw-context-and-event

Please reopen if this doesn't work out for you
