### ISSUE TITLE
Werkzeug updated. Getting errors

### ISSUE THREAD

**Issue by babyhuey** [logandk/serverless-wsgi#179]
On Werkzeug 2.0, getting error: 

`[ERROR] Runtime.ImportModuleError: Unable to import module 'wsgi_handler': No module named 'werkzeug._compat' Traceback (most recent call last):`

**Comment by babyhuey** [comment]
Setting requirement `werkzeug<2` fixes the deployment. 

Looks like it mainly comes from the Python 2 compatibility stuff. Do you want to maintain Py2 compat? Or could I remove that

**Comment by avikalpg** [comment]
I running Python3 (Flask 2.0.0) and still getting this error. 
This is the error that I am getting:

>```[ERROR] ModuleNotFoundError: No module named 'werkzeug._compat' Traceback (most recent call last):   File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler     return user_handler(event, context)   File "/var/task/s_api.py", line 25, in error_handler     raise e   File "/var/task/s_api.py", line 20, in <module>     user_handler = serverless_sdk.get_user_handler('wsgi_handler.handler')   File "/var/task/serverless_sdk/__init__.py", line 56, in get_user_handler     user_module = import_module(user_module_name)   File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import   File "<frozen importlib._bootstrap>", line 991, in _find_and_load   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 783, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/wsgi_handler.py", line 22, in <module>     import serverless_wsgi   File "/var/task/serverless_wsgi.py", line 18, in <module>     from werkzeug._compat import BytesIO, string_types, to_bytes, wsgi_encoding_dance```

**Comment by babyhuey** [comment]
@avikalpg You gotta  go less than 2 `werkzeug<2`. 

Version 1.0.1 is the latest <2 version that works

**Comment by avikalpg** [comment]
Yes, werkzeug<2.0.0 worked for me. I was just mentioning that the problem exists for Python3 as well. So that newer versions of the library can fix this issue.

I had to downgrade my Flask version as well to accommodate this change.

**Comment by shield007** [comment]
I think it makes sense to drop the python 2 support

**Comment by logandk** [comment]
I agree, Python 2 support should be dropped - this will also allow for removal of a some of backwards-compatiblity code and outdated conventions in the library code itself.

**Comment by babyhuey** [comment]
@logandk would you prefer to fix this by pinning `werkzeug<2` in the setup/requirements and make a version 1.7.8 or copy the _compat file over for 1.7.8

I'd like to work separately on creating a version 2.0 that drops support for python2 afterwards as well

**Comment by logandk** [comment]
@babyhuey I think we should pin `werkzeug<2` for 1.7.8 and then release 2.0.0 without python 2 support, as you suggested :+1:

**Comment by babyhuey** [comment]
Great! Looks like someone has already gone through the trouble of pinning to 1.0.1 here
https://github.com/logandk/serverless-wsgi/pull/178

When can we expect you to merge this and create a new release?

**Comment by barrybarrette** [comment]
> 
> 
> Thanks for pointing it out, I missed that PR. Will merge and release asap

Hi @logandk, any update on this? I have a few projects pinned that I'd like to get back to latest on. Anything I can do to move this along?

Thanks

**Comment by shield007** [comment]
I don't think pinning it is a solution, atleast not for me. I'm trying to use latest flask (2.0.1), but with werkzeug pinned I get the following error:
```
The conflict is caused by:
    The user requested werkzeug==1.0.1
    The user requested werkzeug==1.0.1
    flask 2.0.0 depends on Werkzeug>=2.0
```
Makes sense since flask >= 2.0.0 requires newer Werkzeug. This now leaves me having to run old flask as well as werkzeug and probally other stuff over time.

**Comment by akats** [comment]
I'm still getting the same error with flask 2.0.4 with serverless-wsgi v. 1.7.8 .  Any update on supporting Flask 2?

**Comment by logandk** [comment]
The plan was to release serverless-wsgi 2.0.0 which drops Python 2 support and supports the latest Flask/Werkzeug. I don't have any time to allocate towards this in the near future, but I'm happy to accept a PR.

**Comment by Raraku** [comment]
Hi,
I am currently having this error. Is downgrading the only way to go?

**Comment by Raraku** [comment]
Yeah, thanks.
I forgot to update the serverless-wsgi in the package.json. 

My bad

**Comment by tibbe** [comment]
Could somebody please summarize the right way to get this to work with a new Flask and werkzeug? I have installed serverless-wsgi 3.0.0. I currently have:

package.json:
```json
{
  "devDependencies": {
    "serverless-python-requirements": "^5.4.0",
    "serverless-wsgi": "^3.0.0"
  }
}
```

requirements.txt:
```
Flask~=2.1.0
werkzeug~=2.1.1
```

I still get:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'wsgi_handler': No module named 'werkzeug._compat'
```
