### ISSUE TITLE
Default port now taken by MacOS AirPlay to Mac

### ISSUE THREAD

**Issue by p-ackland** [logandk/serverless-wsgi#196]
The default port of 5000 has been taken by AirPlay to Mac in the latest version of MacOS. When running my API locally, no requests were actually making it to the gateway and were instead being denied by the AirPlay receiver process. Given this will probably affect a large number of users and Apple isn't likely to change their end it might make sense to change the default port.

**Comment by selected-pixel-jameson** [comment]
This definitely hung me up for a minute.
