### ISSUE TITLE
Output is incorrect on commands/manage

### ISSUE THREAD

**Issue by babyhuey** [logandk/serverless-wsgi#197]
I have finally upgraded to the latest serverless version.  It looks like they may have changed how promises work? I'm not great with node, but I was able to track down where the issue lies. 

When I run a manage command, the results come back looking like this:
`"Operations to perform:\n  Apply all migrations: admin, analytics, auth, contenttypes, core, sessions\nRunning migrations:\n  No migrations to apply.\n"`

Digging through code, I know that the output is coming from here: https://github.com/logandk/serverless-wsgi/blob/master/index.js#L490

It doesn't appear that the `.then` is getting triggered at all, as when I put in log statements, the output comes before the `.then` gets triggered.

I am going to try to fix it, but I am not great with node, so I could definitely use some help.

Serverless version 2.65.0. serverless-wsgi version 2.0.2

**Comment by babyhuey** [comment]
Did some more digging. The .then is getting triggered, but `output` never gets any data assigned to it

**Comment by babyhuey** [comment]
Got it. It's this change: https://github.com/serverless/serverless/compare/v2.32.1...v2.33.0#diff-5d7f1535c5a73e7da500a1e599a1a125806d8c01b09099b26558911f0af7d78e

**Comment by Warqus** [comment]
What is the status on this? Can this be fixed?

**Comment by babyhuey** [comment]
It's above my skill set right now unfortunately. I think it should be fixable but I don't know enough node to fix it

**Comment by Warqus** [comment]
@babyhuey thanks for the fast reply! That's unfortunate to hear.

**Comment by babyhuey** [comment]
(also note that I am not the maintainer, just a part time contributor and
full time user)

**Comment by logandk** [comment]
I can't find any time to work on this at the moment, happy to accept patches though.

**Comment by babyhuey** [comment]
I will put a $50 bounty to anyone that can fix this. It's very annoying :P

**Comment by babyhuey** [comment]
@logandk I don't mean to be a bother, but can we have a release with this change?

**Comment by logandk** [comment]
@babyhuey Sorry about the delay, I got sidetracked. Thanks for the reminder, the release is out.
