### ISSUE TITLE
AWS Lambda Python 3.6 - need to return a str not bytestring

### ISSUE THREAD

**Issue by eric-tucker** [logandk/serverless-wsgi#21]
https://github.com/logandk/serverless-wsgi/blob/master/wsgi.py#L144

This needs to be changed like was done on the Zappa framework:

https://github.com/Miserlou/Zappa/pull/938/files#diff-b4b0b6c0ef632d8dc89e72cca21a5cdeR448

Otherwise, the hidden wrapper function that Lambda uses fails to json.dumps() the object.

Please resolve ASAP.  We're blocked using Python 3.6.  I'm surprised no one else has complained about this yet.

**Comment by logandk** [comment]
Thanks for reporting, as you noticed there was an ongoing pull request. I was out on vacation for the past weeks, however version 1.2.1 is now available on npm and should address this issue

**Comment by eric-tucker** [comment]
Thanks!!!
