### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by arsoni20** [logandk/serverless-wsgi#218]
Hi, 

I am following this example - https://www.serverless.com/plugins/serverless-wsgi and I am getting an error while deploying my simple flask app to aws 

Error stack - 
(venv) user sls-flask-x % sls deploy      
Running "serverless" from node_modules

Deploying example to stage dev (us-east-1)
Using Python specified in "runtime": python3.8
Packaging Python WSGI handler...
Packaging required Python packages...
Linking required Python packages...

✖ Stack example-dev failed to deploy (7s)
Environment: darwin, node 16.14.2, framework 3.22.0 (local) 3.19.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: ENOTDIR: not a directory, scandir '/Users/username/repo/sls-flask-x/distutils-precedence.pth'

Please suggest to resolve this issue.

**Comment by logandk** [comment]
I think `distutils-precedence.pth` needs to be added here: https://github.com/logandk/serverless-wsgi/blob/master/requirements.py#L85

Can you check if that resolves the issue?

**Comment by arsoni20** [comment]
Hi @logandk your suggestion worked, added 2 more such files in the blacklist list and it worked like a charm. 

raised a PR, please check https://github.com/logandk/serverless-wsgi/pull/219
