### ISSUE TITLE
empty header in event

### ISSUE THREAD

**Issue by cavaunpeu** [logandk/serverless-wsgi#221]
my app, which uses docker, works in lambda.

however, when run locally, and hit with this:

```
CURL --request POST http://localhost:9000/2015-03-31/functions/function/invocations --header 'Content-Type: application/json' -d '{}'
```

continues to give me this error:

``
{"errorMessage": "'headers'", "errorType": "KeyError", "stackTrace": ["  File \"/var/task/app.py\", line 46, in handler\n    return serverless_wsgi.handle_request(app, event, context)\n", "  File \"/var/lang/lib/python3.8/site-packages/serverless_wsgi.py\", line 175, in handle_request\n    return handle_lambda_integration(app, event, context)\n", "  File \"/var/lang/lib/python3.8/site-packages/serverless_wsgi.py\", line 293, in handle_lambda_integration\n    headers = Headers(event[\"headers\"])\n"]}%
```

upon inspection, this is because `event` is an empty dict.

help appreciated, thanks.

**Comment by logandk** [comment]
The endpoint you're using is intended for invoking functions via the AWS SDK or CLI, you need to invoke the function endpoint directly (see the output when running `sls offline`) for serverless-wsgi to get the proper information from the HTTP event
