### ISSUE TITLE
tag 3.0.1 does not contain some fixes from master.

### ISSUE THREAD

**Issue by fernandoanael** [logandk/serverless-wsgi#238]
It seems like 
https://github.com/logandk/serverless-wsgi/blob/master/serverless_wsgi.py#L271 in master 
is not in 3.0.1 https://github.com/logandk/serverless-wsgi/blob/3.0.1/serverless_wsgi.py#L254

This kind of breaks v2 requests with no body. 

Will you release a new version with code from master soon?

Thanks

**Comment by logandk** [comment]
3.0.2 is out now

**Comment by fernandoanael** [comment]
Thanks
