### ISSUE TITLE
Response contain status code and headers

### ISSUE THREAD

**Issue by athioune** [logandk/serverless-wsgi#239]
Hi everyone,

   I'm using the library with AWS Lambda on a Flask application and I have a bug
When I'm returning a json (By using **return make_response(documentJson, 200)**), the return body that I have on Postman contains also the status code and the headers:
![image](https://user-images.githubusercontent.com/12339972/219344697-b95bba50-02e9-4510-822e-fe90fe55fcb4.png)

Do you know how to only return the content of the body ?

Thanks !

**Comment by unkwnownGriot** [comment]
have you tried **return make_response(documentJson, 200)['body']**?

**Comment by athioune** [comment]
Just fixed the problem by adding 
![image](https://user-images.githubusercontent.com/12339972/219403171-ccab053c-af00-4df8-924e-8303c1a2dae8.png)
in the serverless events trigger :)

Thanks !
