### ISSUE TITLE
I got error when I deploy Flask app on AWS lambda 

### ISSUE THREAD

**Issue by parth-patel97** [logandk/serverless-wsgi#240]
Error:

{
    "errorMessage": "'headers'",
    "errorType": "KeyError",
    "stackTrace": [
        "  File \"/var/task/wsgi_handler.py\", line 106, in handler\n    return serverless_wsgi.handle_request(wsgi_app, event, context)\n",
        "  File \"/var/task/serverless_wsgi.py\", line 191, in handle_request\n    return handle_payload_v1(app, event, context)\n",
        "  File \"/var/task/serverless_wsgi.py\", line 198, in handle_payload_v1\n    headers = Headers(event[\"headers\"])\n"
    ]
}

Versions:- 
Running "serverless" from node_modules
Framework Core: 3.28.1 (local) 3.28.1 (global)
Plugin: 6.2.3
SDK: 4.3.2

Python 3.8.0
Flask 1.1.1
Werkzeug 1.0.1

**Comment by Socvest** [comment]
Look into your AWS Cloudwatch service logs for more information. There should be more details about the error there. This just does not provide enough information.
