### ISSUE TITLE
Provide function to execute when calling sls wsgi command

### ISSUE THREAD

**Issue by estahn** [logandk/serverless-wsgi#244]
We run django in AWS Lambda and want to apply database migrations via `sls wsgi manage`. The database user the application runs with is limited and not allowed to create/alter tables. Thus we want to define an alternate Lambda function with different environment variables providing database admin credentials. This is primarily a security concern to segregate the database base user the application uses from the database user the migration script uses.

`findHandler` currently returns the first function with condition `handler: wsgi_handler.handler`.

https://github.com/logandk/serverless-wsgi/blob/master/index.js#L436C7-L440

Instead of returning the first function, if `--function / -f (required)` is specified, the specified function should be used.

**Comment by ayaan-qadri** [comment]
Hey @logandk,

I'm interested in contributing to this issue. I have few questions:

1. Are there any specific guidelines I should follow?
2. Is there existing documentation or resources you recommend?
3. Are there any particular challenges I should be aware of?

Thank you for your help!

**Comment by logandk** [comment]
Hi @ayaan-qadri,
Awesome, any contributions are very welcome.

1. Make sure that the linter is happy and to add test coverage for any new features you add. See the CI pipeline for details on how to run it.
2. You'll need to refer to AWS and/or Serverless documentation. For details about this library, you'll find it inline or in the README.
3. The whole library has been structured around having a single WSGI handler function, so you might need to make some fundamental changes to make this work.

**Comment by ayaan-qadri** [comment]
@logandk Thank you for the answers. I’ll get on this right away.
