### ISSUE TITLE
replace calls to werkzeug.urls with urllib.parse

### ISSUE THREAD

**Issue by wobeng** [logandk/serverless-wsgi#247]
Hello

I noticed in line 17:

`from werkzeug.urls import url_encode, url_unquote, url_unquote_plus`

url_encode, url_unquote, url_unquote_plus is still being imported from werkzeug.urls instead of urllib.parse

**Comment by ghmj2417** [comment]
Also, werkzeug just released 3.0.0 which has removed url_encode (and probably the others) which is breaking serverless-wsgi. Per the deprecation warning. https://github.com/pallets/werkzeug/blob/2.3.7/src/werkzeug/urls.py#L1235

**Comment by dolfno** [comment]
have a hotfix + remove deps ready, but cant create pul request..

**Comment by logandk** [comment]
Happy to accept a PR. @dolfno let me know if I need to do anything, PR's normally work fine on this repo.

**Comment by dolfno** [comment]
am i doing something wrong?
![image](https://github.com/logandk/serverless-wsgi/assets/65344169/87720ca7-9166-4f4e-bb22-0157c78fc7b7)

**Comment by RyanWhittakerTR** [comment]
@logandk I created a PR as I had to fix it earlier anyway on my end, hopefully makes it easy enough. Thanks again for the cool script!
