### ISSUE TITLE
Request for new release based on latest master branch

### ISSUE THREAD

**Issue by cyancey** [logandk/serverless-wsgi#253]
Hello! First of all I wanted to thank @logandk and all contributors for building this for the serverless community.

I am creating this issue to request cutting a new release based on the latest master branch. One of my projects relies on an updated version of Werkzeug and the latest release version (3.0.2) of this plugin has a `url_encode` dependency on an older version of Werkzeug. I confirmed that using the latest master branch ([commit](https://github.com/logandk/serverless-wsgi/commit/d0dca874ebd692849739800d5c47099291d895ea)) resolves my issue and was hoping to point at an official npm release in my dependency file. In the meantime, I can continue work around this by using the github repo as the dependency source. If this is something that I can help with, I'd be happy to assist in the release process.

**Comment by logandk** [comment]
@cyancey 3.03 was released a few days back, including the compatibility update for Werkzeug

**Comment by cyancey** [comment]
Appreciate it! Sorry that I missed that! It wasn't listed as a release in the github repo so I neglected to check npm.
