### ISSUE TITLE
Ubuntu 16.04: support for python3 and virtualenv -p python3

### ISSUE THREAD

**Issue by candlerb** [logandk/serverless-wsgi#29]
I am running under ubuntu 16.04. This has `python3` installed but no `python`.  python(2) is an optional package, and the system doesn't install it by default.  I'd like to keep my system python2-free.

I am trying the sample flask app, and only slightly modified `serverless.yml`:

~~~
service: my-flask

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1

plugins:
  - serverless-wsgi

functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: api.app
~~~

When I try to deploy I get the following error:

~~~
$ serverless deploy -v
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...

  Error --------------------------------------------------

  spawnSync python ENOENT
~~~

There are two places in index.js which have `child_process.spawnSync('python', ...` so I changed them both to `python3`

Now I get a different error:

~~~
  Error --------------------------------------------------

  Unable to load virtualenv, please install
~~~

Fixed by `apt-get install python3-virtualenv`

But now it fails, and the error message is completely blank :-(

~~~
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...

  Error --------------------------------------------------


     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
~~~

Setting SLS_DEBUG=1 I get:

~~~
Error
    at module.exports.logError.errorHandlingError (/usr/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at initializeErrorReporter.then.catch.e (/usr/lib/node_modules/serverless/bin/serverless:42:3)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at __dirname (/usr/lib/node_modules/serverless/bin/serverless:40:9)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
~~~

Still no good. That seems like a bug in its own right - error messages shouldn't be discarded!

So I bring strace to bear:

~~~
strace -s 128 -f serverless deploy -v
...
~~~

and now I see the error:

~~~
[pid  5633] read(21, "The executable python2 (from --python=python2) does not exist\n", 65536) = 62
~~~

Using virtualenv in Ubuntu requires `virtualenv -p python3`

Modified `requirements.py`:

~~~
    sys.argv = ['', venv_dir, '--quiet', '-p', 'python3']
~~~

After this, deployment works, phew.

I'm not sure of the right clean fix.  Maybe there should be a setting  like`custom.wsgi.python: python3` which overrides both the binary and adds the `-p` option to virtualenv?

**Comment by candlerb** [comment]
FYI, I found a similar issue at https://github.com/UnitedIncome/serverless-python-requirements/issues/72 prior to their 3.0.0 beta version. (That project is derived from serverless-wsgi)

The approach they seem to take is:

- the "runtime" setting is used as the binary name: e.g. if your runtime is set to "python3.6" then it tries to execute the command "python3.6" locally too.
- this can be overridden with a `pythonBin` option

    ~~~
    custom:
      pythonRequirements:
        pythonBin: /usr/bin/python3.5
    ~~~

- the same setting is used for virtualenvs

    ~~~
    ./index.js:      const res = spawnSync('pipenv', ['--python', runtime, 'install']);
    ./index.js:      const res = spawnSync('pipenv', ['--python', runtime, '--venv']);
    ./index.js:      const res = spawnSync('pipenv', ['--python', runtime, '--venv']);
    ~~~

**Comment by logandk** [comment]
Thanks for the detailed research, I agree that adding the necessary options for configuring virtualenv is probably the cleanest fix. The packaging part of this plugin is definitely the area that most often trigger issues due to platform differences etc. Making it more configurable is probably better than trying to cope with all these quirks behind the scenes.
