### ISSUE TITLE
Insecure usage of X-Forwarded-For

### ISSUE THREAD

**Issue by candlerb** [logandk/serverless-wsgi#36]
serverless-wsgi currently sets the `REMOTE_ADDR` variable like this:

~~~
        'REMOTE_ADDR':
            headers.get(u'X-Forwarded-For', '').split(', ')[0],
~~~

But that's insecure, since anyone can submit a request with their own `X-Forwarded-For:` header, containing one or more IPs.  API gateway will append to the end of this, so the header becomes:

~~~
X-Forwarded-For: <spoofed-address(es)>, <real-source>, <api-gateway>
~~~

and `REMOTE_ADDR` will be set to the first spoofed address.

What should be returned is `<real-source>`, which you can get via:

~~~
        'REMOTE_ADDR':
            headers.get(u'X-Forwarded-For', '').split(', ')[-2],
~~~

Of course that will fail if for some reason the header is missing or broken, so safer would be:

~~~
ips = headers.get(u'X-Forwarded-For', '').replace(' ','').split(',')
if len(ips) == 1:
    remote_addr = ips[0]
else:
    remote_addr = ips[-2]

...
        'REMOTE_ADDR':
            remote_addr
~~~

Another option is to use `event["requestContext"]["identity"]["sourceIp"]`, although I've not tested whether that is spoofable or not.

**Comment by logandk** [comment]
Good catch, let's check if `event["requestContext"]["identity"]["sourceIp"]` is spoofable

**Comment by logandk** [comment]
I just checked (x.x.x.x is my ip, I'm attempting to spoof it with 10.2.3.4). I'm getting:

```
"X-Forwarded-For": "10.2.3.4, x.x.x.x, y.y.y.y"
```

Exactly as you described. However, `event["requestContext"]["identity"]["sourceIp"]` remain unspoofed:

```
"sourceIp": "x.x.x.x"
```
