### ISSUE TITLE
Unable to access raw lambda 'event'

### ISSUE THREAD

**Issue by candlerb** [logandk/serverless-wsgi#37]
Using Flask, I cannot see a way to access the raw 'event' from within a function, although the 'context' is available:

~~~
        'context':
            context,
~~~

So for example, I can't get to low-level things like `event["requestContext"]["identity"]["sourceIp"]`

Have I overlooked something? Otherwise, could it be added like this:

~~~
        'event':
            event,
~~~

**Comment by logandk** [comment]
Indeed, it is not accessible through the request at the moment, we should add it
