### ISSUE TITLE
Binary Data - multipart/form-data Support

### ISSUE THREAD

**Issue by umerebryx** [logandk/serverless-wsgi#44]
I am trying to setup a flask app using serverless-wsgi plugin on aws lambda. I am using api gateway proxy integration and have also enabled this content type in Binary Support. All my POST request's are getting through except for the ones with content-type multipart/form-data.

Does your plugin support Binary data via API gateway? If it does how would I get the contents of my file using flask request module:
Normally I can use below to save a file locally on my server:

> data = request.files['customer_speech_file']
> data.save('/tmp/' + str(data.filename))

**Comment by logandk** [comment]
Hi, I realized that there was an issue with calculating the content length for binary payloads. I think this is why your `multipart/form-data` endpoints were not working.

Please try out version `1.4.2` and report back (make sure to have binary support for `multipart/form-data` enabled). If it still fails, please log `request.environ` during a failing request and include in your report.
