### ISSUE TITLE
breakpoint debugging

### ISSUE THREAD

**Issue by hlarsen** [logandk/serverless-wsgi#58]
using 'wsgi serve' definitely helps speed up development, but i'm looking into running the project directly with a line by line debguger (pydev). it appears i'm having an issue due to environment variables not being read in by serverless as they are when using 'wsgi serve'.

not a big problem to overcome, but i thought i'd ask if there are any recommendations for debugging with breakpoints.

**Comment by logandk** [comment]
Could you give an example of how env vars are not working properly? How are you setting the env vars, where are they being read and what is the specific issue?

**Comment by logandk** [comment]
I think this may be the closest thing to an off-the-shelf solution for this purpose: https://github.com/arabold/serverless-export-env

**Comment by logandk** [comment]
I'd suggest using that plugin to generate the `.env` file, load it into your shell and start the debugging process. Wrapping those steps up in a shell script, npm task or Makefile should be pretty quick.
