### ISSUE TITLE
lambda event and context

### ISSUE THREAD

**Issue by JadyNews** [logandk/serverless-wsgi#59]
Hi ,

Following by the blog post, https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/#converting-an-existing-flask-application.

Just wondering how can I get the lambda event and context ? can I just ```print event``` as below?
tried but it did not work

I would appreciate it if anyone can help.

```
# app.py
import os
import boto3

from flask import Flask, jsonify, request
app = Flask(__name__)

event = os.environ['event']
print event

if IS_OFFLINE:
    client = boto3.client(
        'dynamodb',
        region_name='localhost',
        endpoint_url='http://localhost:8000'
    )
else:
    client = boto3.client('dynamodb')

@app.route("/")
def hello():
    return jsonify(os.environ)
... rest of application code ...
```

**Comment by logandk** [comment]
Hi,
You can get access through `request.environ['context']` and `request.environ['event']`. I'll leave this issue open as a reminder to add this to the README.
