### ISSUE TITLE
Release this as a pypi module

### ISSUE THREAD

**Issue by frob** [logandk/serverless-wsgi#63]
Any chance this could be released as a standalone python module. Looks like it could be really useful outside the serverless framework.

**Comment by logandk** [comment]
I'm interested to hear your thoughts on how this plugin would be useful outside the Serverless framework? Considering that https://github.com/Miserlou/Zappa exists, which does both APIGW/WSGI mapping and deployment without Serverless, I'm not sure that there's much more to offer by releasing this on PyPI.

**Comment by logandk** [comment]
Closing, please reopen if you still think this would be helpful.

**Comment by frob** [comment]
It would be handy, because there doesn't exist any real good way to deal with APIGW -> wsgi outside of a full stack deployment system. All these frameworks; serverless, Zappa, Chalice, they are all designed to take over the deployment as well as work as a framework. 

All I want is reliable apigw -> wsgi conversion.

**Comment by logandk** [comment]
That makes sense, I agree that it could be useful.
