### ISSUE TITLE
sls wsgi serve returns "Unable to import werkzeug"

### ISSUE THREAD

**Issue by DJuboor** [logandk/serverless-wsgi#64]
Currently, the "sls wsgi serve" command has an error when calling wsgi.

It will return: "Unable to import werkzeug (run: pip install werkzeug)"
even though the werkzeug requirement is in the requirements.txt file of the wsgi package.

The steps to directly reproduce on a fresh Ubuntu 16.04 VirtualBox Install can be found here:
https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/

Just for kicks: 
-I installed werkzeug locally and sudo cp'd it into the serverless-wsgi main directory and there was another requirement that needed to be installed (boto3, botocore, click, etc). I did this for a couple of iterations before coming here.
-I pip installed everything needed for the ^^ dependency tree failure in a virtualenv and pip freezed the venv into the serverless-wsgi requirements.txt , also no avail.

**Comment by logandk** [comment]
Ubuntu 16.04 comes with Python 3.5 by default. The `sls wsgi serve` command will run the Lambda `runtime` python version by default, i.e. `python3.6`. So chances are you've set up your venv and run pip install under Python 3.5 and `sls wsgi serve` is running under Python 3.5 and thus not finding your packages.

You can customize your python binary using the following option, as described in the README:

```
custom:
  wsgi:
    app: api.app
    pythonBin: python3
```

However, preferably, ensure that your virtualenv and pip install is running under Python 3.6, so you run under the same version as Lambda.

**Comment by maxcountryman** [comment]
Is there any way to make this play nice with `pyenv`?
