### ISSUE TITLE
support python3.7

### ISSUE THREAD

**Issue by andrewkrug** [logandk/serverless-wsgi#66]
When running in python3.7 virtualenv this throws:

```
spawnSync python3.6 ENOENT
```

**Comment by logandk** [comment]
For now, you can use the `pythonBin` option to set your local python executable: https://github.com/logandk/serverless-wsgi#python-version

I'm leaving this open, as it would be nice to improve the detection of the local python executable, automatically fallback to available versions and provide more helpful error messages.
