### ISSUE TITLE
Local Server Running Slow

### ISSUE THREAD

**Issue by GazEdge** [logandk/serverless-wsgi#69]
When I run `serverless wsgi serve` I'm having problems with the requests taking a long time (10seconds - 1min) to return a response. Sometimes the response will not return at all. To avoid hitting a database I'm sending GET request to a route that immediately returns 'hello world' 200.

So far the only predictable behaviour I can find is that making a request using jquery will always cause a long delay before returning. If I try to request the same URL in the browser tab (whilst the jquery request is still waiting) the tab also waits a long time for for the request to return.

However, once the jquery request returns, calling the URL in a browser tab then returns immediately. Refreshing the tab gives a response immediately.

Sometimes, if jquery request is pending, calling the URL in a browser tab WILL return immediately. When this happens, this seem to also make the jquery request return a response.

Jquery code below:
```javascript
      $( document ).ready(function() {
        $.get("http://localhost:5000/test", function(data, status){
          alert("Data: " + data + "\nStatus: " + status);
        });
      });
```

I've tried restarting the server, browsers and my machine, but the problem still persists.

I've tried multiple browsers (safari, chrome, firefox) and all have the same issue.

I've tried making a javascript request using axios instead of jquery but still the requests are returning slowly.

Does anyone have any idea how I might solve this or any additional debugging I can do? 

I'm using:
- serverless-wsgi 1.4.9
- node 5.6.0
- macOS 10.12

**Comment by logandk** [comment]
The `sls wsgi serve` command is a thin wrapper around Werkzeug's HTTP server. First off, you should try to start your app directly on your local machine, without using `serverless-wsgi`, and check if the issue persists. If the issue only occurs when using `sls wsgi serve`, please provide a simple reproduction example (Python app with an endpoint, requirements.txt, serverless.yml and instructions on how to trigger slow requests consistently)

**Comment by GazEdge** [comment]
Thanks - I've done as you said. Problem persists, but I can make it go away by setting threaded = True when running the WSGI server. 

It doesn't seem like its possible to pass a threaded param to `serverless wsgi serve`. 

If I mod the serve.py to the below, my issue goes away:
```
    serving.run_simple(
        host, int(port), wsgi_app, use_debugger=True, use_reloader=True, use_evalex=True, threaded=True
    )

```

**Comment by logandk** [comment]
Nice work, thanks for looking into this! I'll add the `threaded` flag and push a new version
