### ISSUE TITLE
Map authorizer custom keys

### ISSUE THREAD

**Issue by ProTip** [logandk/serverless-wsgi#7]
Custom authorizers have a serious flaw in that they can not return headers. This means that the CORS header can not be set for 401's.

To work around this I will "allow" every request, but include the authorization status and reason(missing token, invalid token, expired, etc) in the authorizer context. However serverless-wsgi does not currently extract those keys.

I would like to setup a way to extract these authorizer keys...

**Comment by logandk** [comment]
Zappa has a simple solution for this issue: https://github.com/Miserlou/Zappa/blob/master/zappa/wsgi.py#L111

It will extract the principal ID and user ARN from the request context and pass it through WSGI using a custom header. I suggest adopting the exact same convention for this library...

**Comment by ProTip** [comment]
I have ended up wrapping ```wsgi.handler``` with my own entrypoint. It extracts all of the authorizer keys and adds them to the headers before calling ```wsgi.handler```.

If anyone wants to do this be careful because lambda has a system path setup with ```wsgi.handler``` in it! I used ```imp.load_source``` to get around this.
