### ISSUE TITLE
Unable to import module 'wsgi': No module named 'werkzeug'

### ISSUE THREAD

**Issue by HoneyryderChuck** [logandk/serverless-wsgi#71]
I started having this issue today when deploying python lambda functions, and it's hard to say what caused this, since I didn't update any relevant configuration. The cloudwatch logs also only show:

```
Unable to import module 'wsgi': No module named 'werkzeug'
```

with no other backtrace, and this seems to happen before my application code is evaluated. I also tried to revert to the latest stable release, and it also doesn't work.

Did something in AWS change which caused this error?

**Comment by HoneyryderChuck** [comment]
@logandk thx for the reply. 

I'm using docker, so I (assume that) don't need virtualenv.

This is what I did:

* built the package (`sls package --stage staging --package build`).
* unzipped the package (`unzip -a build/myapp.zip`).
* ran `python wsgi`

and I got no error (function terminated with no error exit code).

So now I'm kinda lost... do you know how I could debug my setup using the AWS lambda console? This seems not to be helping.

**Comment by HoneyryderChuck** [comment]
We've managed to download the artifact which has failed, and we've noticed some differences, namely the presence of a `serverless_wsgi.py` file in the root. In fact, if I try to run `wsgi.py`, I see the error importing wekzeug coming exactly from this file. And I also see that it was introduced 5 days ago.

**Comment by HoneyryderChuck** [comment]
So, my `package.json` had the dependency set as `^1.4.6`, which I assumed it would only upgrade minor patches. but apparently my builds were installing 1.5.0, which apparently introduced the aforementioned file, and broke my function invocation (even before it was invoked). 

I fixed my issue by downgrading to `1.4.9` and fixing my `package.json`, but AFAIK this is still an issue, so will keep it open.

**Comment by jplock** [comment]
This was fixed in v1.5.1
