### ISSUE TITLE
Add MIME `image/svg+xml` to default whitelist

### ISSUE THREAD

**Issue by GazEdge** [logandk/serverless-wsgi#74]
Spent a good few hours trying to work out why an `image/svg+xml` MIME was returning garbage:

Should return something like:
`<?xml version="1.0"?><svg width="1125" height="432" xmlns=...`

But was returning:
`PD94bWwgdmVyc2lvbj0iMS4wIj8 ....`

I then read the following in the docs:

> Text MIME types
By default, all MIME types starting with text/ and the following whitelist are sent through API Gateway in plain text. **All other MIME types will have their response body base64 encoded** (and the isBase64Encoded API Gateway flag set) in order to be delivered by API Gateway as binary data.

It then dawned on me that `image/svg+xml` needs to be returned as text, not binary (like most images).

Fixed by adding the following to serverless.yml:
```
    textMimeTypes:
    - image/svg+xml
```
Whilst this may be an edge case, it may be helpful to add `image/svg+xml` to the whitelist as I went round and round in circles in my attempt to solve this.

Since SVG images are mainly used in use cases where you need to real-time build an image in code (instead of serving one directly from s3) its seems like a good fit for the whitelist in my opinion.

**Comment by logandk** [comment]
I agree, this is common enough that it makes sense to add it by default.
