### ISSUE TITLE
Unable to invoke manage commands on deployed Django application

### ISSUE THREAD

**Issue by gsmith077** [logandk/serverless-wsgi#75]
Is there a way to run CLI commands on the deployed application? A primary example of where this would be needed would be invoking a "manage" command for django, like collectstatic.
Something like `serverless manage "collectstatic --no-input"` would be ideal.

As it stands, running commands like this is not possible using serverless-wsgi, or at least isn't clearly defined how to do so.

**Comment by logandk** [comment]
This is not currently supported, but I think it's a great idea and I'll go ahead and implement it soon.

**Comment by jplock** [comment]
I worked around this by putting the unzip_requirements import into manage.py and then creating a handler method to create a separate lambda to interface with manage. It mostly worked. :)

**Comment by ptrhck** [comment]
I would like to handle django settings as environment variables in my serverless.yml, which works great when doing `sls wsgi serve -s local`. It would be a great feature if one could access django management commands with sls wsgi and the desired environment variables.
