### ISSUE TITLE
Need to pass '--no-deps' to the pip install command in requirements.py

### ISSUE THREAD

**Issue by lestephane** [logandk/serverless-wsgi#76]
My requirements.txt is frozen, and I don't want the pip install to pull some python 2 dependencies (my lambda runtime is python3).

Concrete example:
```bash
(make new virtualenv)
$ pip-install python-jose
$ pip freeze > requirements.txt 
$ cat requirements.txt 
ecdsa==0.13
future==0.17.1 <<<<<<<<< remove this line (python2 only, size is 1.5 megs)
pyasn1==0.4.4
python-jose==3.0.1
rsa==4.0
six==1.11.0
```

This is a matter of keeping the lambda function zip file size down. But if I do this currently, the serverless-wsgi plugin re-pulls the (transitive) `future` dependency. I don't want that.

A quick test shows that my code would still work without the `future` dependency.

```bash
$  pip uninstall future
Uninstalling future-0.17.1:
(...)
Proceed (y/n)? y
  Successfully uninstalled future-0.17.1
$ python
Python 3.6.6 (default, Aug 26 2018, 13:00:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jose import jwt
>>> token = jwt.encode({'key': 'value'}, 'secret', algorithm='HS256')
>>> print(token)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJ2YWx1ZSJ9.JPIDicqvQ6GAh14yE2yZ3wnZQ0LiLNTTRDtJgLZcn98
```

Could a capability be added to pass `--no-deps` to the pip install command-line run in requirements.py? Maybe a way to pass pip command-line arguments through the `serverless.yml`'s `custom:` section, or some environment variable?

I'll try the python-requirements plugin to see what happens there.

**Comment by logandk** [comment]
Adding the ability to pass additional arguments to pip sounds reasonable, I agree
