### ISSUE TITLE
Set stage for django management commands

### ISSUE THREAD

**Issue by ptrhck** [logandk/serverless-wsgi#79]
I was trying the new django management commands.

My serverless.yml contains environmental variables for different stages and in order to run the wsgi server locally I do: `sls wsgi serve -s local`.

I would also like to execute the django management commands locally such as with ` sls wsgi manage -c "check --list-tags" -s local`.

It seems to not work out as I get the following error:

`Function not found: arn:aws:lambda:eu-central-1:xxxxxx:function:cookbook-local-app`

Is this just not possible or am I missing something?

**Comment by logandk** [comment]
@ptrhck Yeah, as opposed to `sls wsgi serve`, which only operates locally, `sls wsgi manage` relies on `sls invoke` and thus only works remotely. We could add a `sls wsgi manage local -c "..."` (allowing you to add the stage parameter as well, if desired). Do you see any issues with this approach in relation to your use-case?

**Comment by ptrhck** [comment]
For my use case this would be a great feature. Currently my workaround is to load the environment variables with https://github.com/colynb/serverless-dotenv-plugin and the export them from the resulting .env. Afterwards I can use the django management commands as desired. If you could add the stage parameter so I can can call `sls wsgi manage -c "check --list-tags" -s local`, the workaround of exporting the variables from serverless.yml to a dotenv file would be obsolete.
