### ISSUE TITLE
Unable to invoke flask cli commands

### ISSUE THREAD

**Issue by shughes-uk** [logandk/serverless-wsgi#86]
I'm not sure if this is a bug or a feature request but trying to invoke any flask cli commands via 'sls wsgi command' results in an error. It would make my life much easier if there was a way to get them working.

`Traceback (most recent call last):
  File "/var/task/wsgi.py", line 82, in handler
    meta.get("data", ""), shell=True, stderr=subprocess.STDOUT
  File "/var/lang/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/var/lang/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'flask' returned non-zero exit status 127.`

Cheers!

**Comment by logandk** [comment]
@shughes-uk Yeah, command line scripts from packages, such as the `flask` command aren't available. 

I'll look into either:

- Making a flask cli specific command like we have for django management commands
- Get command line scripts into the bundle and in the `PATH` as well (which will probably still break in many cases due to environment differences on lambda)

**Comment by revmischa** [comment]
```
sls wsgi flask -c routes                                      
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 97, in handler
    obj=ScriptInfo(create_app=_create_app),
  File "/var/task/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/task/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/var/task/click/core.py", line 1188, in resolve_command
    ctx.fail('No such command "%s".' % original_cmd_name)
  File "/var/task/click/core.py", line 496, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: No such command "routes".
```

I can't seem to run any flask commands. Getting the same thing with `flask local`.

**Comment by logandk** [comment]
Yes, this only works for your custom flask commands at the moment, not those that are part of the `flask-cli` tool. I'll see if there's a way to load the default cli commands as well.

**Comment by revmischa** [comment]
I can't seem to access any custom commands either. I can't run any flask commands.

This is my code: https://github.com/jetbridge/sls-flask

I can run `flask init-db` just fine, but:
```
⇒ sls wsgi flask -c init-db -s test
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 97, in handler
    obj=ScriptInfo(create_app=_create_app),
  File "/var/task/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/task/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/var/task/click/core.py", line 1188, in resolve_command
    ctx.fail('No such command "%s".' % original_cmd_name)
  File "/var/task/click/core.py", line 496, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: No such command "init-db".
```

It would really make my life easier if this worked!

**Comment by logandk** [comment]
I suspect that the app factory pattern is what's causing it not to work in your case, @revmischa. Will need to figure out what's needed to get it working. I haven't had time to look into this recently, and it will be some more weeks until I'll find the time myself. If you find a solution in the meantime, please submit it.

**Comment by revmischa** [comment]
`sls wsgi flask -c config` fails (`config` is a custom command)
`sls wsgi flask local -c config` succeeds?
`sls wsgi flask local -c routes` fails (`routes` is built in)

i want to help figure out what's wrong but i'm pretty lost. the flask CLI docs don't make things much clearer for me. any ideas of things to try?
i need to get this resolved to hook up flask-migrate/alembic for serverless

**Comment by revmischa** [comment]
weird thing i found:
if i invoke `myapp.cli.main()` in normal virtualenv then it runs `main` from `.../site-packages/flask/cli.py` as expected
but if invoked as a lambda, then somehow myapp.cli.main is resolving to `main` from `click/core.py`
why would myapp.cli be click not flask.cli?

**Comment by logandk** [comment]
Thanks for your effort, @revmischa. I just had some time to look into this today and merged your PR (#99)

Both local and remote invocations of custom and built-in commands appear to work now. Closing this issue for now, please re-open if it's still now working for your use case.

**Comment by revmischa** [comment]
I still have the same issue in master

Built-in commands now work at least:
```
⇒ sls wsgi flask  -c routes     
Endpoint                      Methods  Rule
----------------------------  -------  -----------------------
Authentication.check_auth     GET      /api/auth/check
Authentication.login          POST     /api/auth/login
Authentication.refresh_token  POST     /api/auth/refresh
Monitoring.Monitoring         GET      /api/monitoring
api-docs.openapi_json         GET      /api/openapi.json
api-docs.openapi_redoc        GET      /api/doc
api-docs.openapi_swagger_ui   GET      /api/swagger
static                        GET      /static/<path:filename>
```

But non built in commands do not, such as flask-migrate:
```
⇒ sls wsgi flask -c db     
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 96, in handler
    shlex.split(meta.get("data", "")), standalone_mode=False
  File "/var/task/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/var/task/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/task/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/var/task/click/core.py", line 1188, in resolve_command
    ctx.fail('No such command "%s".' % original_cmd_name)
  File "/var/task/click/core.py", line 496, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: No such command "db".
```

I suspect the issue may be related to the fact I do not see any of my code in this traceback, as mentioned above:
> if i invoke `myapp.cli.main()` in normal virtualenv then it runs `main` from `.../site-packages/flask/cli.py` as expected
> but if invoked as a lambda, then somehow myapp.cli.main is resolving to `main` from `click/core.py`
> why would myapp.cli be click not flask.cli?

**Comment by revmischa** [comment]
And even stranger, `flask local` works
```
sls wsgi flask local -c db
"Usage: invoke.py db [OPTIONS] COMMAND [ARGS]...\n\n  Perform database migrations.\n\nOptions:\n  --help  Show this message and exit.\n\nCommands:\n  branches   Show current branch points\n  current    Display the current revision for each database.\n  downgrade  Revert to a previous version\n  edit       Edit a revision file\n  heads      Show current available heads in the script directory\n  history    List changeset scripts in chronological order.\n  init       Creates a new migration repository.\n  merge      Merge two revisions together, creating a new revision file\n  migrate    Autogenerate a new revision file (Alias for 'revision...\n  revision   Create a new revision file.\n  show       Show the revision denoted by the given symbol.\n  stamp      'stamp' the revision table with the given revision; don't run...\n  upgrade    Upgrade to a later version\n"
```

**Comment by logandk** [comment]
@revmischa I'm assuming you're using `app.debug` here... Please reopen if not

**Comment by revmischa** [comment]
Hah! you appear to be totally correct. thanks!
