### ISSUE TITLE
Static images don't render

### ISSUE THREAD

**Issue by johnnymetz** [logandk/serverless-wsgi#88]
I have the following folder structure:

    root
        serverless.yml
        app.py
        templates
            index.html
        static
            my_image.png
            styles.css

serverless.yml

    service: sl-wsgi-img

    plugins:
      - serverless-python-requirements
      - serverless-wsgi

    custom:
      wsgi:
        app: app.app
        packRequirements: false
      pythonRequirements:
        dockerizePip: true

    provider:
      name: aws
      runtime: python3.6
      stage: dev
      region: us-west-2

    functions:
      app:
        handler: wsgi_handler.handler
        events:
          - http:
              path: '/'
              method: ANY
          - http:
              path: '/{proxy+}'
              method: ANY

app.py

    from flask import Flask, render_template

    app = Flask(__name__)

    @app.route("/", methods=["GET"])
    def index():
        return render_template("index.html")

index.html

    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" name='styles.css') }}"/>
        <title>Document</title>
      </head>
      <body>
        <h1>Hello World</h1>
        <img src="{{ url_for('static', filename='my_image.jpg') }}" alt="Dexter Image" width="200px"/>
      </body>
    </html>

styles.css

    h1 {
      color: red;
    }

When I run the app locally with `sls wsgi serve` or `flask run` everything works as expected as I hit the home route:

<img width="292" alt="Screen Shot 2019-03-13 at 10 26 07 PM" src="https://user-images.githubusercontent.com/20693145/54333267-0e36b280-45df-11e9-9fd9-a978a1de0ef5.png">

However, when I deploy the basic app the image doesn't render:

<img width="180" alt="Screen Shot 2019-03-13 at 10 27 26 PM" src="https://user-images.githubusercontent.com/20693145/54333305-36261600-45df-11e9-85ce-11047ad666bb.png">

The strange thing here is `styles.css` works fine both locally and on aws. Any idea what the problem with images may be?

**Comment by logandk** [comment]
API Gateway requires you to register the mime-types that you'd like to serve as binary responses. See https://github.com/logandk/serverless-wsgi#text-mime-types - in particular this: *remember to add any binary MIME types that you're using to the Binary Support list in API Gateway*

You can do this automatically with the [serverless-apigw-binary](https://github.com/maciejtreder/serverless-apigw-binary) plugin

**Comment by use-sparingly** [comment]
It would seem that API GW is very fussy about the request "Accept" header. 

When Binary types included `image/png`, I was finding that:

     $ curl https://xxxx.execute-api.eu-west-1.amazonaws.com/dev/img/my.png -H "Accept: */*"
     �PNG....

would work and return binary, but using no Accept header or Chrome's accept headers would return Base64:

    $ curl https://xxxx.execute-api.eu-west-1.amazonaws.com/dev/img/my.png -H "accept: image/*,*/*;q=0.8"
    iVBORw0KG.....

**After finding a few AWS forums on the subject, it would appear the solution is to set the binary types to just:**

     */*

**I then had to redeploy and clear the cache of my browser to make it work.**

E.g. using serverless-apigw-binary:

    custom:
      wsgi:
        app: server.app
        packRequirements: false
      pythonRequirements:
        dockerizePip: non-linux
      apigwBinary:
        types:
          - '*/*'

**Comment by morgan-young** [comment]
@alastairmccormack I was just googling for a solution and your advice solved the problem. Thanks!
