### ISSUE TITLE
Wrong formatting of ouputs from management commands

### ISSUE THREAD

**Issue by ptrhck** [logandk/serverless-wsgi#89]
If I do for e.g. `sls wsgi manage local -c "check --list-tags"`, the output is not printed in seperate lines but as follows in one line: `"admin\ncaches\ndatabase\nmodels\nstaticfiles\ntemplates\nurls\n"`.

Is this OS related, as your docs suggests the right format? I am using docker with `FROM python:3.6-stretch`. 

Any idea?

**Comment by logandk** [comment]
So far, I haven't been able to reproduce this. I get the output in multiple lines, both when invoking locally and remotely.

How does it look when you run a regular `sls invoke local` with the `data` flag set to `{"_serverless-wsgi":{"command":"manage","data":"check --list-tags"}}`?

**Comment by ptrhck** [comment]
Adding the following to the Dockerfile solved the problem:

```
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
```

**Comment by ptrhck** [comment]
I am still facing a problem. First of all regarding your question:

```
root@b8afcabb2495:/app# sls wsgi manage local -c "check --list-tags" -s local
admin
caches
database
models
staticfiles
templates
urls
root@b8afcabb2495:/app# sls invoke local -f app --data '{"_serverless-wsgi":{"command":"manage","data":"check --list-tags"}}' -s local
"admin\ncaches\ndatabase\nmodels\nstaticfiles\ntemplates\nurls\n"
```

I have some trouble using custom commands. It is no problem running them, but the output is only printed when the command has finished. With the regular manage.py it prints my output continously, which is very helpful for logging purposes. Moreover, the output is still formated differently.

Some test command:

```
from django.core.management.base import BaseCommand, CommandError
import logging
import time

class Foo:
    def __init__ (self):
        self._logger = logging.getLogger(__name__)
    def call(self):
        for i in range(10):
            self._logger.info('loop ' + str(i))
            time.sleep(1)
        pass


class Command(BaseCommand):

    def add_arguments(self, parser):
        pass

    def handle(self, *args, **options):
        try:
            foo = Foo()
            foo.call()
        except Exception as e:
            raise CommandError(e)
```

You can see the difference here:

```
root@b8afcabb2495:/app# python manage.py test
loop 0
loop 1
loop 2
loop 3
loop 4
loop 5
loop 6
loop 7
loop 8
loop 9
root@b8afcabb2495:/app# sls wsgi manage local -c "test" -s local
loop 0

loop 1

loop 2

loop 3

loop 4

loop 5

loop 6

loop 7

loop 8

loop 9

""
```

It would be great to see the same output that is being printed continously.

**Comment by ptrhck** [comment]
I am posting this issue here as it might be related to this topic. When calling `sls wsgi manage local -c "test" -s local`, the following error occurs:

`Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.`

**Comment by logandk** [comment]
We're using Serverless' built-in invoke functionality, which doesn't allow us to run commands in an interactive TTY, so I don't see any way to resolve your last issue within the scope of this plugin (I don't want to reimplement `sls invoke` and thus make it non-composable for other plugins).

Regarding output formatting, I agree that it should print the exact same way.

Continuous output of captured process output for local invocation would be nice, but it adds significant complexity, especially since we support both Python 2 and 3. And since it only applies locally, it's not something I'm going to spend time implementing at this point. If you'd like to take it on, please send a PR.

**Comment by logandk** [comment]
Finally had a chance to look into why your output was different when running `sls wsgi manage local` versus `manage.py` directly. AFAICT, it's because the WSGI logging configuration differs from the regular Django logging configuration.
