### ISSUE TITLE
Serverless WSGI - with Sentry

### ISSUE THREAD

**Issue by mprzytulski** [logandk/serverless-wsgi#91]
Is there a way of using that plugin together with Sentry? 
I tried a bottle framework together with official SDK https://docs.sentry.io/platforms/python/bottle/ but it looks like it works only for first request and if lambda is cached on AWS we not getting any errors.

**Comment by logandk** [comment]
I'm haven't looked into how Sentry hooks into your WSGI app, but AWS Lambda doesn't do caching. It will however reuse an existing container, so if you invoke any code outside of your request handler, it will only get invoked once per container. I believe that your issue isn't directly related to this plugin and should be resolved with Sentry instead, so I'm closing it - but feel free to reopen if you find out that this is not correct.
