### ISSUE TITLE
Question: Monkey Patching wsgi_handler.py

### ISSUE THREAD

**Issue by ajinabraham** [logandk/serverless-wsgi#96]
I have seen this: https://github.com/logandk/serverless-wsgi#usage-without-serverless
But let's say I want to install serverless-wsgi with serverless framework and not via pip.
Is there a standard way I can add some custom code to `wsgi_handler.py`. I can see it get created, bundled in the zip and deleted with an `sls deploy`. I wanted to know if I can add some custom code, monkey patch some functions etc in `wsgi_handler.py`

**Comment by logandk** [comment]
@ajinabraham Normally, you'd do this kind of thing as WSGI middleware. If that's not applicable to your use case, you could add your own `custom_wsgi_handler.py` file and set that as the handler in `serverless.yml`. Then import and patch whatever you need from `wsgi_handler.py` in `custom_wsgi_handler.py`.
